/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import formImage from '../public/form.jpg'
import { useFormik } from 'formik'
import * as Yup from 'yup'
import { useRouter } from 'next/router'
import { motion as m } from 'framer-motion'

export default function Home() {
  const router = useRouter();

  const formik = useFormik({
    initialValues: {
      name: '',
      email: '',
      country: 'Latvia',
      terms: ''
    },
    validationSchema: Yup.object({
      name: Yup.string()
        .max(20, 'Name must be 20 characters or less.')
        .required('Name is required'),
      email: Yup.string()
        .email('Invalid email adress')
        .required('Email is required'),
      terms: Yup.array()
        .required('Terms of service must be checked')
    }),
    onSubmit: (values) => {
      console.log(formik.values)
      router.push({ pathname: '/success', query: values })
    }
  });


  return (
    <m.div initial={{opacity: 0}} animate={{opacity: 1}} exit={{opacity: 0}} className='absolute w-full'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-screen flex items-center justify-center'>
        <form onSubmit={formik.handleSubmit} className='bg-white flex rounded-lg w-1/2'>
          <div className='flex-1 text-gray-700 p-20'>
            <h1 className='text-3xl pb-2 font-bold'>
              Let's get started
            </h1>
            <p className='text-lg text-gray-500'>
              Join our E-learning platform today and unlock over 500+ courses and digital assets ready to download.
            </p>
            <div className='mt-6'>
              <div className='pb-4'>
                <label className={`block font-bold text-sm pb-2 ${formik.touched.name && formik.errors.name ? 'text-red-400' : ''}`} htmlFor="name">
                  {formik.touched.name && formik.errors.name ? formik.errors.name : 'Name'}
                </label>
                <input 
                className='border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500'
                value={formik.values.name}
                onChange={formik.handleChange}
                onBlur={formik.handleBlur}
                id='name' 
                type="text" 
                name='name' 
                placeholder='Enter your name' />
              </div>
              <div className='pb-4'>
                <label className={`block font-bold text-sm pb-2 ${formik.touched.email && formik.errors.email ? 'text-red-400' : ''}`} htmlFor="email">
                  {formik.touched.email && formik.errors.email ? formik.errors.email : 'Email'}
                </label>
                <input 
                className='border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500' 
                id='email' 
                value={formik.values.email}
                onChange={formik.handleChange}
                onBlur={formik.handleBlur}
                type="email" 
                name='email' 
                placeholder='Enter your email' />
              </div>
              <div className='pb-4'>
                <label className='block font-bold text-sm pb-2' htmlFor="contry">
                  Country
                </label>
                <select 
                  name='country'
                  value={formik.values.country}
                  onChange={formik.handleChange}
                  className='border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500 cursor-pointer' 
                  id='country'>
                  <option>United States</option>
                  <option>United Kingdom</option>
                  <option>Germany</option>
                  <option>Norway</option>
                  <option>Latvia</option>
                </select>
              </div>
              <div className='pb-4'>
                <label className={`block font-bold text-sm pb-2 ${formik.touched.terms && formik.errors.terms ? 'text-red-400' : ''}`} htmlFor="terms">
                  {formik.touched.terms && formik.errors.terms ? formik.errors.terms : 'Terms of service'}
                </label>
                <div className='flex items-center gap-2'>
                  <input 
                    type="checkbox" 
                    name='terms' 
                    value='checked'
                    onChange={formik.handleChange}
                    className='h-5 w-5 outline-transparent text-teal-500 border-2 focus:border-teal-500 focus:ring-teal-500 cursor-pointer' 
                    id='terms'
                  />
                  <label htmlFor="terms">
                    I agree to the Terms and Service that my data will be taken and sold.
                  </label>
                </div>
              </div>
              <button className='bg-teal-500 font-bold text-sm text-white py-3 mt-6 rounded-lg w-full cursor-pointer hover:bg-teal-700'>Start learning today!</button>
            </div>
          </div>
          <div className='flex-1 relative'>
            <Image sizes='100%' src={formImage} priority fill alt='form learn' className='object-cover rounded-lg' />
          </div>
        </form>
      </main>
    </m.div>
  )
}
